
USE nidevs00_dev

BEGIN TRY
		BEGIN TRAN
		--CREAR TABLAS PARA PAGINA WEB
		CREATE TABLE T_PERSON(
		PERSON_ID BIGINT PRIMARY KEY IDENTITY,
		PERSON_NAME VARCHAR(50) NOT NULL,
		LAST_NAME VARCHAR(50) NOT NULL,
		PERSON_AGE INT NOT NULL,
		CREATE_DATE DATETIME NOT NULL,
		DISABLE_DATE DATETIME NULL,
		PERSON_STATUS BIT,
		NATIONALITY_ID BIGINT
		)

		CREATE TABLE T_USER(
		USER_ID BIGINT PRIMARY KEY IDENTITY,
		PERSON_ID BIGINT FOREIGN KEY REFERENCES T_PERSON(PERSON_ID),
		USER_LOGIN VARCHAR(25),
		USER_PASSWORD VARBINARY(64), 
		CREATE_DATE DATETIME NOT NULL,
		DISABLE_DATE DATETIME NULL,
		USER_STATUS BIT
		)
		ALTER TABLE T_USER
		ADD CONSTRAINT CK_PASS_LENGHT
		CHECK ( LEN(USER_PASSWORD) BETWEEN 8 AND 20 )

		CREATE TABLE T_EMAIL(
		EMAIL_ID BIGINT PRIMARY KEY IDENTITY,
		EMAIL_MAIL VARCHAR(50),
		PERSON_ID BIGINT FOREIGN KEY REFERENCES T_PERSON(PERSON_ID), 
		CREATE_DATE DATETIME NOT NULL,
		DISABLE_DATE DATETIME NULL,
		EMAIL_STATUS BIT
		)
		CREATE TABLE T_PHONE(
		PHONE_ID BIGINT PRIMARY KEY IDENTITY,
		PERSON_ID BIGINT FOREIGN KEY REFERENCES T_PERSON(PERSON_ID),
		PHONE_NUMBER VARCHAR(10),
		CREATE_DATE DATETIME NOT NULL,
		DISABLE_DATE DATETIME NULL
		)

		CREATE TABLE T_ADDRESS(
		ADDRESS_ID BIGINT PRIMARY KEY IDENTITY,
		PERSON_ID BIGINT FOREIGN KEY REFERENCES T_PERSON(PERSON_ID),
		ADDRESS_DESCRIPTION VARCHAR(250),
		CREATE_DATE DATETIME NOT NULL,
		DISABLE_DATE DATETIME NULL
		)

		CREATE TABLE T_TOPIC(
		TOPIC_ID BIGINT PRIMARY KEY IDENTITY,
		PERSON_ID BIGINT FOREIGN KEY REFERENCES T_PERSON(PERSON_ID),
		TOPIC_NAME VARCHAR(50),
		CREATE_DATE DATETIME NOT NULL,
		DISABLE_DATE DATETIME NULL
		)

		CREATE TABLE T_POST(
		POST_ID BIGINT PRIMARY KEY IDENTITY,
		TOPIC_ID BIGINT FOREIGN KEY REFERENCES T_TOPIC(TOPIC_ID),
		POST_COMMENT VARCHAR(1000),
		PERSON_ID BIGINT REFERENCES T_PERSON(PERSON_ID),
		CREATE_DATE DATETIME NOT NULL,
		DISABLE_DATE DATETIME NULL
		)

END TRY
BEGIN CATCH
 SELECT
        ERROR_NUMBER() AS ErrorNumber
        ,ERROR_SEVERITY() AS ErrorSeverity
        ,ERROR_STATE() AS ErrorState
        ,ERROR_PROCEDURE() AS ErrorProcedure
        ,ERROR_LINE() AS ErrorLine
        ,ERROR_MESSAGE() AS ErrorMessage;
ROLLBACK TRAN
END CATCH
COMMIT TRAN